using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

using UnityEngine;

using SysRandom = System.Random;

/// <summary>
/// Provides parameter generation services for a room generator
/// </summary>
public abstract class ParameterBuilder : ScriptableObject
{
    [Tooltip("The generators available rooms")]
    public RoomLayoutCollection Rooms;

    [Tooltip("The weapons that can spawn in the room")]
    public List<WeaponTemplate> WeaponTemplates;

    [Header("Enemies")]
    [Tooltip("The enemies that can spawn grounded in the room")]
    public List<RoomParameters.EnemyWithSpawnRate> GroundEnemies;

    [Tooltip("The enemies that can spawn airborne in the room")]
    public List<RoomParameters.EnemyWithSpawnRate> AirEnemies;

    /// <summary>
    /// Gets the next room parameters to use when generating a room
    /// </summary>
    /// <param name="history"></param>
    /// <param name="random"></param>
    /// <returns></returns>
    public abstract RoomParameters GetNextParameters(RoomHistory history, SysRandom random);

    /// <summary>
    /// Gets the room parameters for the first room generated by a generator
    /// </summary>
    /// <param name="random"></param>
    /// <returns></returns>
    public abstract RoomParameters GetInitialParameters(SysRandom random);
}
